name: Build Debian Persistent XFCE ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  iso-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Build ISO inside privileged Docker container
      - name: Build ISO in privileged Docker
        run: |
          docker run --rm --privileged \
            -v "${{ github.workspace }}:/work" \
            -w /work \
            debian:trixie /bin/bash -c "
              set -e
              apt-get update &&
              apt-get install -y --no-install-recommends \
                live-build xorriso squashfs-tools p7zip-full \
                grub-efi-amd64-bin mtools dosfstools rsync \
                apt-utils gnupg2 ca-certificates git &&
              chmod +x mkiso.sh &&
              ./mkiso.sh
            "

      # Step 3: Upload ISO artifact
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-trixie-xfce-persistent
          path: live-build-workdir/*.iso
